// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-side compaction fired during this turn.
 */
export type CompactedEvent = { time: string, 
/**
 * Full usage object from the API response (structure varies; kept verbatim).
 */
usage: unknown, };
