// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";
import type { ContextHash } from "./ContextHash";
import type { Role } from "./Role";

/**
 * The on-disk shape of a single `context.jsonl` record.
 *
 * Extends a conversation message with persistence metadata.
 */
export type ContextRecord = { 
/**
 * Unique primary key: 12 lowercase hex characters (6 random bytes).
 */
hash: ContextHash, 
/**
 * ISO 8601 UTC timestamp when this record was appended.
 */
time: string, 
/**
 * Role of the message author.
 */
role: Role, 
/**
 * Content blocks of the message.
 */
content: Array<ContentBlock>, };
