// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single content block inside a [`Message`].
 *
 * Mirrors the Anthropic Messages API shape — the union of every block
 * type the agent sends or receives.
 */
export type ContentBlock = { "type": "text", text: string, } | { "type": "thinking", thinking: string, signature?: string, } | { "type": "tool_use", id: string, name: string, 
/**
 * Arbitrary JSON input parameters supplied by the LLM.
 */
input: unknown, } | { "type": "tool_result", tool_use_id: string, content: string, is_error?: boolean, };
