// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 12-character lowercase hex string encoding 6 random bytes.
 *
 * Serves as the primary key of `context.jsonl` records and as a foreign key
 * in `events.jsonl`.  Construct with [`random_hash`] or validate an existing
 * string with [`hash_from_str`].
 */
export type ContextHash = string;
