// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The operator changed the thinking effort level.
 */
export type EffortChangedEvent = { time: string, effort: string, };
