// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `TurnInterruptedEvent.reason` discriminator.
 */
export type InterruptReason = "aborted" | "error";
