// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An outgoing API call to an LLM.
 */
export type LlmCallEvent = { time: string, url: string, model: string, 
/**
 * Ordered hashes of every context record in the sent context.
 */
contextHashes: Array<string>, 
/**
 * Index (0-based) of the message that received the cache breakpoint.
 * Always serialized (as `null` when absent) — not `skip_serializing_if`.
 */
cacheBreakpointIndex: number | null, 
/**
 * Serialized byte size of the full request payload.
 */
requestBytes: number, requestSummary?: unknown, };
