// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-retryable LLM provider call error.
 */
export type LlmErrorEvent = { time: string, url: string, error: string, httpStatus?: number, };
