// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage from an LLM response envelope.  Field names intentionally
 * kept in `snake_case` to match the Anthropic API's wire format.
 */
export type LlmResponseUsage = { input_tokens: number, output_tokens: number, 
/**
 * Tokens written to the prompt cache this call (billed at 1.25× base).
 */
cache_creation_input_tokens?: number, 
/**
 * Tokens served from the prompt cache this call (billed at 0.1× base).
 */
cache_read_input_tokens?: number, 
/**
 * Service tier used; absent or `"standard"` is the baseline.
 */
service_tier?: string, };
