// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmResponseUsage } from "./LlmResponseUsage";

/**
 * An LLM response received by the agent.
 */
export type LlmResponseEvent = { time: string, stopReason: string, clearedToolUses?: number, clearedInputTokens?: number, usage: LlmResponseUsage, 
/**
 * FK into `context.jsonl` for the assistant record written for this response.
 */
contextHash: string, 
/**
 * Full assembled assistant text, if any.
 */
text?: string, 
/**
 * Full assembled thinking content, if any (multiple blocks concatenated).
 */
thinking?: string, 
/**
 * ISO timestamp of the first streaming text delta.
 */
streamingStart?: string, responseSummary?: unknown, };
