// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmRetryReason } from "./LlmRetryReason";

/**
 * LLM provider call retried after a transient error.
 */
export type LlmRetryEvent = { time: string, 
/**
 * Retry attempt number, 1-based.
 */
attempt: number, httpStatus?: number, 
/**
 * Milliseconds to wait before the next attempt.
 */
waitMs: number, error: string, retryAt?: string, 
/**
 * Full structured error body from the provider, kept verbatim.
 */
errorBody?: unknown, 
/**
 * Partial thinking content accumulated before the error.
 */
thinkingFragment?: string, 
/**
 * Partial text content accumulated before the error.
 */
textFragment?: string, 
/**
 * Why the retry fired.  Absent for ordinary policy-driven retries.
 */
reason?: LlmRetryReason, };
