// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `LlmRetryEvent.reason` discriminator.
 */
export type LlmRetryReason = "retry-after";
