// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The operator switched the active model.
 */
export type ModelChangedEvent = { time: string, model: string, };
