// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentErrorEvent } from "./AgentErrorEvent";
import type { CompactedEvent } from "./CompactedEvent";
import type { EffortChangedEvent } from "./EffortChangedEvent";
import type { LlmCallEvent } from "./LlmCallEvent";
import type { LlmErrorEvent } from "./LlmErrorEvent";
import type { LlmResponseEvent } from "./LlmResponseEvent";
import type { LlmRetryEvent } from "./LlmRetryEvent";
import type { ModelChangedEvent } from "./ModelChangedEvent";
import type { PauseRequestedEvent } from "./PauseRequestedEvent";
import type { ResumingSessionEvent } from "./ResumingSessionEvent";
import type { ServerStartedEvent } from "./ServerStartedEvent";
import type { ServerStoppedEvent } from "./ServerStoppedEvent";
import type { SessionResumedEvent } from "./SessionResumedEvent";
import type { SessionStartedEvent } from "./SessionStartedEvent";
import type { ToolCallEvent } from "./ToolCallEvent";
import type { ToolResultEvent } from "./ToolResultEvent";
import type { TransportErrorEvent } from "./TransportErrorEvent";
import type { TurnContinuedEvent } from "./TurnContinuedEvent";
import type { TurnEndEvent } from "./TurnEndEvent";
import type { TurnInterruptedEvent } from "./TurnInterruptedEvent";
import type { TurnPausedEvent } from "./TurnPausedEvent";
import type { UserMessageEvent } from "./UserMessageEvent";

/**
 * The single unified event type for Omega.
 *
 * Every `OmegaEvent` is both streamed to UI consumers and written to
 * `.omega/sessions/<timestamp>/events.jsonl`.
 *
 * The `"type"` JSON field is the discriminator; values are `snake_case`
 * (e.g. `"session_started"`, `"tool_call"`).
 */
export type OmegaEvent = { "type": "session_started" } & SessionStartedEvent | { "type": "server_started" } & ServerStartedEvent | { "type": "server_stopped" } & ServerStoppedEvent | { "type": "user_message" } & UserMessageEvent | { "type": "llm_call" } & LlmCallEvent | { "type": "llm_response" } & LlmResponseEvent | { "type": "tool_call" } & ToolCallEvent | { "type": "tool_result" } & ToolResultEvent | { "type": "turn_end" } & TurnEndEvent | { "type": "llm_error" } & LlmErrorEvent | { "type": "agent_error" } & AgentErrorEvent | { "type": "turn_interrupted" } & TurnInterruptedEvent | { "type": "compacted" } & CompactedEvent | { "type": "llm_retry" } & LlmRetryEvent | { "type": "model_changed" } & ModelChangedEvent | { "type": "effort_changed" } & EffortChangedEvent | { "type": "transport_error" } & TransportErrorEvent | { "type": "resuming_session" } & ResumingSessionEvent | { "type": "session_resumed" } & SessionResumedEvent | { "type": "pause_requested" } & PauseRequestedEvent | { "type": "turn_paused" } & TurnPausedEvent | { "type": "turn_continued" } & TurnContinuedEvent;
