// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user has requested a pause.
 */
export type PauseRequestedEvent = { time: string, };
