// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session resumption has started — basis extracted, LLM call about to fire.
 */
export type ResumingSessionEvent = { time: string, resumedFrom: string, name?: string, basis: string, };
