// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Role of a [`Message`] in the conversation history.
 */
export type Role = "user" | "assistant";
