// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ServerStoppedEvent.outcome` discriminator.
 */
export type ServerStopOutcome = "clean" | "error";
