// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerStopOutcome } from "./ServerStopOutcome";

/**
 * The server process stopped cleanly.
 */
export type ServerStoppedEvent = { time: string, outcome: ServerStopOutcome, reason?: string, };
