// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The session started (first event in every session).
 */
export type SessionStartedEvent = { time: string, sessionId: string, 
/**
 * Session directory path relative to the Omega root (cwd).
 */
path: string, model: string, effort: string, 
/**
 * The full system prompt text at session start.
 */
systemPrompt: string, 
/**
 * Short git commit hash of the Omega source at the time the binary was built.
 * `"unknown"` when git was unavailable at build time.
 * Defaulted on deserialise so that events written before this field was
 * added still parse successfully (backward compat).
 */
omegaCommit: string, };
