// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The session was seeded with a summary of a previous session.
 */
export type SessionResumedEvent = { time: string, resumedFrom: string, summary: string, };
