// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for a session.  All fields are optional.
 *
 * Written as JSONC so humans can add comments when editing manually.
 * Programmatic writes use plain JSON (a valid subset of JSONC).
 */
export type SessionMetadata = { 
/**
 * Short human-readable label.
 */
name?: string, 
/**
 * Free-text description.
 */
description?: string, 
/**
 * Relative folder name of the session this one resumes.
 * `continuationOf` is accepted as a legacy alias.
 */
resumedFrom?: string, };
