// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A raw streaming fragment from the LLM.  Never persisted.
 */
export type StreamSignal = { "type": "text", text: string, } | { "type": "thinking", text: string, };
