// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool invocation by the agent.
 */
export type ToolCallEvent = { time: string, id: string, name: string, 
/**
 * Tool input parameters (arbitrary JSON from the LLM).
 */
input: unknown, 
/**
 * Hash of the assistant context.jsonl record containing this `tool_use` block.
 */
contextHash: string, };
