// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a tool invocation.
 */
export type ToolResultEvent = { time: string, id: string, name: string, isError: boolean, durationMs: number, 
/**
 * Full text output of the tool.
 */
output: string, };
