// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transport-layer error emitted by the web server.
 */
export type TransportErrorEvent = { time: string, error: string, context?: string, };
