// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContinueMode } from "./ContinueMode";

/**
 * The paused turn is resuming.
 */
export type TurnContinuedEvent = { time: string, mode: ContinueMode, };
