// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The agent has reached a clean seam and the turn is now paused.
 */
export type TurnPausedEvent = { time: string, };
