// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnMetrics } from "./TurnMetrics";

/**
 * End of a user turn — aggregate metrics.
 */
export type TurnEndEvent = { time: string, metrics: TurnMetrics, };
