// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterruptReason } from "./InterruptReason";

/**
 * The user interrupted an in-flight turn, or the turn ended due to an error.
 */
export type TurnInterruptedEvent = { time: string, reason?: InterruptReason, };
