// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-turn aggregate token and cache metrics.  Used by [`TurnEndEvent`].
 */
export type TurnMetrics = { inputTokens: number, outputTokens: number, cacheCreationTokens?: number, cacheReadTokens?: number, };
