// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user message submitted to the agent.
 */
export type UserMessageEvent = { time: string, content: string, };
