//! [`ToolCtx`] — session-scoped context threaded from the agent loop into
//! each tool execution.
//!
//! `ToolCtx` carries:
//! * `cache_dir` — so every tee log / download cache lands inside the
//!   session directory tree rather than in `$TMPDIR` or the current working
//!   directory.
//! * `system_prompt_paths` — canonical paths of files already embedded in
//!   the system prompt; `execute_tool` checks this before dispatching
//!   `read_file` and short-circuits with an informative message when the
//!   requested file is already present.
//!
//! ## Invariant
//! All paths constructed by tools via `ToolCtx::cache_dir` must resolve
//! within `sessions_root/<session-id>/cache/`.  Benchmarks run with
//! `cwd=/app` (the verifier's territory); any stray writes there would
//! corrupt the harness.  The test suite enforces this with
//! `no_tee_output_escapes_sessions_root` in `process_tools.rs`.

use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::monitors::MonitorManager;
use crate::python_repl::PythonRepl;

/// Session-scoped execution context passed to every tool invocation.
#[derive(Debug, Clone)]
pub struct ToolCtx {
    /// Base directory for all tee logs and caches produced during this
    /// session.  Always equals `<sessions_root>/<session-id>/cache/`.
    ///
    /// Tools join sub-directories off this path:
    /// * `cache_dir/run/`   — `run_command` tee logs
    /// * `cache_dir/wait/`  — `wait_for_output` snapshots
    /// * `cache_dir/fetch/` — `fetch_url` downloaded files
    pub cache_dir: PathBuf,

    /// Omega-issued identifier for this specific tool invocation.
    ///
    /// Generated by the agent dispatch loop (not by the LLM provider), so it
    /// is provider-agnostic.  Used as part of the tee-log filename so that
    /// a log file and its corresponding `events.jsonl` entry are
    /// bidirectionally cross-referenceable by a simple string search — the
    /// same value appears as `toolCallId` on `ToolUseBlockEvent`,
    /// `ToolCallEvent`, and `ToolResultEvent`.
    ///
    /// Format: 8 lowercase hex characters (4 random bytes).
    pub tool_call_id: String,

    /// Canonical paths of every file already embedded in the system prompt
    /// (i.e. every [`SystemBlock`](omega_agent::system_prompt::SystemBlock)
    /// that has a `source_path`).  Populated by `Agent::init` and cloned
    /// into every `ToolCtx` via `Arc`.
    ///
    /// `execute_tool` checks this before dispatching `read_file`: if the
    /// resolved path is present the call is short-circuited with a message
    /// telling the model the content is already available, saving a
    /// potentially large token-consuming redundant read.
    pub system_prompt_paths: Arc<HashSet<PathBuf>>,

    /// Shared handle to the session's Python REPL state.
    ///
    /// `Some(…)` when `features.repl = true` for this session; `None` otherwise.
    ///
    /// The outer `Option` controls feature availability: `None` means REPL is
    /// disabled and the `python_repl` tool returns an error.  The inner
    /// `Option<PythonRepl>` supports lazy startup: `None` means the subprocess
    /// has not yet been started; it is started on the first `python_repl` tool
    /// call and reused for all subsequent calls in the session.
    ///
    /// The `Arc<Mutex<…>>` allows the same subprocess handle to be shared
    /// across concurrent tool dispatches (concurrent `python_repl` calls are
    /// serialised by the mutex — correct because the REPL is inherently
    /// sequential).
    pub python_repl: Option<Arc<tokio::sync::Mutex<Option<PythonRepl>>>>,

    /// Names of the tools selected for this session.
    ///
    /// Controls selection-gated tool behaviour (e.g. when no shell-execution
    /// tool is in this list, `fetch_url` switches to a postprocess-free
    /// schema and refuses to run a shell pipeline).  Defaults to the empty
    /// vector when constructed via [`ToolCtx::new`]; the agent populates
    /// this with the live session's `tool_selection` for every dispatch.
    pub tool_selection: Vec<String>,

    /// Shared handle to the session's async-monitor runtime (pending queue +
    /// roster).  `Some(…)` when monitors are enabled for this session;
    /// `None` otherwise (the `monitor` / `stop_monitor` tools then return an
    /// error).
    ///
    /// The agent's main loop owns the same `Arc` so it can drain the pending
    /// queue at boundaries (Phase 2) and reap all process trees on session
    /// end via [`MonitorManager::shutdown`].  Cloning the `Arc` into each
    /// `ToolCtx` is what lets the `monitor` tool push to the manager the
    /// loop later drains — the single ownership seam between the two phases.
    ///
    /// Phase 1 leaves this `None` in production (the tools are not yet
    /// exposed to the model — clean-cutover); tests populate it explicitly.
    pub monitors: Option<Arc<MonitorManager>>,
}

impl ToolCtx {
    /// Build a `ToolCtx` whose cache root is `session_dir.join("cache")`
    /// and an empty `system_prompt_paths` set.
    ///
    /// `session_dir` is typically the value stored in `AgentConfig::session_dir`.
    /// `tool_call_id` is the Omega-issued per-invocation identifier (8-char hex);
    /// it appears verbatim in `events.jsonl` and as the tee-log filename stem.
    ///
    /// Tests and callers that do not need the system-prompt guard can use
    /// this constructor; the guard is simply inactive when the set is empty.
    #[must_use]
    pub fn new(session_dir: &Path, tool_call_id: impl Into<String>) -> Self {
        Self {
            cache_dir: session_dir.join("cache"),
            tool_call_id: tool_call_id.into(),
            system_prompt_paths: Arc::new(HashSet::new()),
            python_repl: None,
            tool_selection: Vec::new(),
            monitors: None,
        }
    }
}
