//! Usage panel — collapsible, sticky token-usage display above the composer.
//!
//! ## Structure
//!
//! ```text
//! App
//!  ├── provide_context::<UsagePanelOpen>
//!  └── UsagePanel           ← renders above Composer, visibility gated by
//!       ├── usage-table      UsagePanelOpen
//!       │    ├── header row: [turn | in (uncached) | in (cache write) |
//!       │    │                       in (cache read) | out | ⓘ]
//!       │    ├── turn row    (last completed turn, or live accumulation)
//!       │    └── session row (session-total, incl. live if streaming)
//!       └── TokenLegend      ← fixed-position overlay toggled by ⓘ
//! ```
//!
//! ## Pure helpers (mutation-tested)
//!
//! - [`last_turn_counts`]  — finds the last `TurnEnd` event's metrics
//! - [`live_turn_counts`]  — sums `LlmResponse` usages since last `UserMessage`
//! - [`session_counts`]    — sums all `TurnEnd` metrics across the session
//!
//! All three operate on the flat `Vec<OmegaEvent>` already held by the
//! `SessionStore`, so no new store signals are needed.

use leptos::ev;
use leptos::prelude::*;
use omega_protocol::OmegaEvent;

use crate::store::SessionStore;

// ---------------------------------------------------------------------------
// Context: panel open/close toggle
// ---------------------------------------------------------------------------

/// Wraps the open/close boolean for the usage panel. Provided as context
/// from `App`; consumed by `Composer` (toggle button) and `UsagePanel`
/// (conditional rendering).
#[derive(Debug, Clone, Copy)]
pub struct UsagePanelOpen(pub RwSignal<bool>);

impl UsagePanelOpen {
    /// Construct closed state. Must run inside a leptos reactive `Owner`.
    #[must_use]
    pub fn new() -> Self {
        Self(RwSignal::new(false))
    }

    /// Toggle open ↔ closed.
    #[mutants::skip] // reactive signal write; covered by e2e harness.
    pub fn toggle(self) {
        self.0.update(|v| *v = !*v);
    }

    /// Whether the panel is currently open.
    pub fn is_open(self) -> bool {
        self.0.get()
    }
}

impl Default for UsagePanelOpen {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Token count accumulator — pure data
// ---------------------------------------------------------------------------

/// Token breakdown for one logical unit (a turn or the whole session).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct TokenCounts {
    /// Input tokens processed fresh (not from prompt cache).
    pub fresh_in: i64,
    /// Input tokens written into the prompt cache (cache-creation cost).
    pub cache_write_in: i64,
    /// Input tokens served from the prompt cache (cache-read cost).
    pub cache_read_in: i64,
    /// Output tokens generated by the model.
    pub out: i64,
}

impl TokenCounts {
    /// Add `other` to `self` field-by-field.
    #[must_use]
    pub fn add(self, other: Self) -> Self {
        Self {
            fresh_in: self.fresh_in + other.fresh_in,
            cache_write_in: self.cache_write_in + other.cache_write_in,
            cache_read_in: self.cache_read_in + other.cache_read_in,
            out: self.out + other.out,
        }
    }
}

/// Returns the most-recent completed turn's token counts by finding the
/// last `TurnEnd` event in the slice. Returns `None` when no `TurnEnd`
/// has been seen yet.
pub fn last_turn_counts(events: &[OmegaEvent]) -> Option<TokenCounts> {
    events.iter().rev().find_map(|ev| {
        if let OmegaEvent::TurnEnd(e) = ev {
            Some(TokenCounts {
                fresh_in: e.metrics.input_tokens,
                cache_write_in: e.metrics.cache_creation_tokens.unwrap_or(0),
                cache_read_in: e.metrics.cache_read_tokens.unwrap_or(0),
                out: e.metrics.output_tokens,
            })
        } else {
            None
        }
    })
}

/// Accumulates `LlmResponse` token usage since the most recent
/// `UserMessage`. Returns zero counts when no `LlmResponse` has been
/// seen in the current turn yet (e.g. streaming hasn't reached the first
/// response boundary).
pub fn live_turn_counts(events: &[OmegaEvent]) -> TokenCounts {
    let start = events
        .iter()
        .rposition(|ev| matches!(ev, OmegaEvent::UserMessage(_)))
        .map(|i| i + 1)
        .unwrap_or(0);

    let mut acc = TokenCounts::default();
    for ev in &events[start..] {
        if let OmegaEvent::LlmResponse(e) = ev {
            acc.fresh_in += e.usage.input_tokens;
            acc.cache_write_in += e.usage.cache_creation_input_tokens.unwrap_or(0);
            acc.cache_read_in += e.usage.cache_read_input_tokens.unwrap_or(0);
            acc.out += e.usage.output_tokens;
        }
    }
    acc
}

/// Sums token counts from every `TurnEnd` event in the slice. This gives
/// the session-lifetime total for completed turns (live turn added by the
/// caller when streaming).
pub fn session_counts(events: &[OmegaEvent]) -> TokenCounts {
    let mut acc = TokenCounts::default();
    for ev in events {
        if let OmegaEvent::TurnEnd(e) = ev {
            acc.fresh_in += e.metrics.input_tokens;
            acc.cache_write_in += e.metrics.cache_creation_tokens.unwrap_or(0);
            acc.cache_read_in += e.metrics.cache_read_tokens.unwrap_or(0);
            acc.out += e.metrics.output_tokens;
        }
    }
    acc
}

// ---------------------------------------------------------------------------
// UsagePanel component
// ---------------------------------------------------------------------------

/// Non-modal sticky panel rendered above the composer row.
/// Visibility is toggled by the "Usage" button in [`crate::composer::Composer`].
///
/// Marked `#[mutants::skip]` — the reactive/DOM body is exercised by the
/// e2e harness; the three pure derivation functions carry the mutation-test
/// budget.
#[mutants::skip]
#[component]
pub fn UsagePanel() -> impl IntoView {
    let store = use_context::<SessionStore>().expect("SessionStore must be provided");
    let panel_open =
        use_context::<UsagePanelOpen>().expect("UsagePanelOpen must be provided");

    // Legend overlay — local to the panel; no context needed.
    let legend_open = RwSignal::new(false);

    // Derive turn counts reactively.
    let turn_row = Memo::new(move |_| {
        let streaming = store.streaming.get();
        store.events.with(|evs| {
            if streaming {
                Some(live_turn_counts(evs))
            } else {
                last_turn_counts(evs)
            }
        })
    });

    // Derive session counts reactively (incl. live turn when streaming).
    let sess_row = Memo::new(move |_| {
        let streaming = store.streaming.get();
        store.events.with(|evs| {
            let base = session_counts(evs);
            if streaming {
                base.add(live_turn_counts(evs))
            } else {
                base
            }
        })
    });

    view! {
        <Show when=move || panel_open.is_open() fallback=|| ()>
            <div class="usage-panel" data-testid="usage-panel">
                <table class="usage-table">
                    <thead>
                        <tr>
                            <th class="ut-row-label ut-header"></th>
                            <th class="ut-header">"in (uncached)"</th>
                            <th class="ut-header">"in (cache write)"</th>
                            <th class="ut-header">"in (cache read)"</th>
                            <th class="ut-header ut-gap">"out"</th>
                            <th class="ut-legend-cell ut-header">
                                <button
                                    class="ut-legend-btn"
                                    data-testid="usage-legend-btn"
                                    title="Token field legend"
                                    on:click=move |_| legend_open.update(|v| *v = !*v)
                                >"ⓘ"</button>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        // Turn row — absent until the first turn completes or starts.
                        {move || turn_row.get().map(|c| view! {
                            <tr data-testid="usage-turn-row">
                                <td class="ut-row-label">"turn"</td>
                                <td class="ut-val">{c.fresh_in}</td>
                                <td class="ut-val">{c.cache_write_in}</td>
                                <td class="ut-val">{c.cache_read_in}</td>
                                <td class="ut-val ut-gap">{c.out}</td>
                                <td />
                            </tr>
                        })}
                        // Session row — always present once panel is open.
                        {move || {
                            let c = sess_row.get();
                            view! {
                                <tr data-testid="usage-session-row">
                                    <td class="ut-row-label">"session"</td>
                                    <td class="ut-val">{c.fresh_in}</td>
                                    <td class="ut-val">{c.cache_write_in}</td>
                                    <td class="ut-val">{c.cache_read_in}</td>
                                    <td class="ut-val ut-gap">{c.out}</td>
                                    <td />
                                </tr>
                            }
                        }}
                    </tbody>
                </table>
                <TokenLegend legend_open=legend_open />
            </div>
        </Show>
    }
}

// ---------------------------------------------------------------------------
// TokenLegend sub-component
// ---------------------------------------------------------------------------

/// Fixed-position overlay explaining each token column.
/// Rendered inside `UsagePanel`; toggled by the ⓘ button.
#[component]
fn TokenLegend(legend_open: RwSignal<bool>) -> impl IntoView {
    view! {
        <Show when=move || legend_open.get() fallback=|| ()>
            <div
                class="token-legend-overlay"
                data-testid="token-legend-overlay"
                on:click=move |_| legend_open.set(false)
            >
                <div
                    class="token-legend"
                    on:click=move |e: ev::MouseEvent| e.stop_propagation()
                >
                    <div class="token-legend-header">
                        <span>"Token fields"</span>
                        <button
                            class="token-legend-close"
                            data-testid="token-legend-close"
                            on:click=move |_| legend_open.set(false)
                        >"✕"</button>
                    </div>
                    <table class="token-legend-table">
                        <tbody>
                            <tr>
                                <td><code>"in (uncached)"</code></td>
                                <td>"Tokens processed fresh (standard rate)"</td>
                            </tr>
                            <tr>
                                <td><code>"in (cache write)"</code></td>
                                <td>"Tokens written into prompt cache (1.25×)"</td>
                            </tr>
                            <tr>
                                <td><code>"in (cache read)"</code></td>
                                <td>"Tokens served from prompt cache (0.1×)"</td>
                            </tr>
                            <tr>
                                <td><code>"out"</code></td>
                                <td>"Tokens generated by the model"</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </Show>
    }
}

// ---------------------------------------------------------------------------
// Tests — pure derivation functions only
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::panic)]

    use super::*;
    use omega_protocol::events::{
        LlmResponseEvent, LlmResponseUsage, TurnEndEvent, TurnMetrics, UserMessageEvent,
    };

    fn user_msg(content: &str) -> OmegaEvent {
        OmegaEvent::UserMessage(UserMessageEvent {
            time: "t".into(),
            content: content.into(),
        })
    }

    fn turn_end(fresh: i64, cw: i64, cr: i64, out: i64) -> OmegaEvent {
        OmegaEvent::TurnEnd(TurnEndEvent {
            time: "t".into(),
            metrics: TurnMetrics {
                input_tokens: fresh,
                output_tokens: out,
                cache_creation_tokens: if cw == 0 { None } else { Some(cw) },
                cache_read_tokens: if cr == 0 { None } else { Some(cr) },
            },
        })
    }

    fn llm_response(fresh: i64, cw: i64, cr: i64, out: i64) -> OmegaEvent {
        OmegaEvent::LlmResponse(LlmResponseEvent {
            time: "t".into(),
            stop_reason: "end_turn".into(),
            cleared_tool_uses: None,
            cleared_input_tokens: None,
            usage: LlmResponseUsage {
                input_tokens: fresh,
                output_tokens: out,
                cache_creation_input_tokens: if cw == 0 { None } else { Some(cw) },
                cache_read_input_tokens: if cr == 0 { None } else { Some(cr) },
                service_tier: None,
            },
            context_hash: "abc".into(),
            text: None,
            thinking: None,
            streaming_start: None,
            response_summary: None,
        })
    }

    // ── last_turn_counts ──────────────────────────────────────────────────

    #[test]
    fn last_turn_counts_none_when_no_events() {
        assert!(last_turn_counts(&[]).is_none());
    }

    #[test]
    fn last_turn_counts_none_when_only_user_message() {
        let evs = vec![user_msg("hi")];
        assert!(last_turn_counts(&evs).is_none());
    }

    #[test]
    fn last_turn_counts_returns_last_turn_end_metrics() {
        let evs = vec![
            turn_end(10, 0, 0, 5),
            user_msg("hi"),
            turn_end(20, 3, 1, 8),
        ];
        let c = last_turn_counts(&evs).unwrap();
        assert_eq!(c.fresh_in, 20);
        assert_eq!(c.cache_write_in, 3);
        assert_eq!(c.cache_read_in, 1);
        assert_eq!(c.out, 8);
    }

    #[test]
    fn last_turn_counts_none_optional_cache_fields_default_to_zero() {
        let evs = vec![turn_end(7, 0, 0, 3)];
        let c = last_turn_counts(&evs).unwrap();
        assert_eq!(c.cache_write_in, 0);
        assert_eq!(c.cache_read_in, 0);
    }

    // ── live_turn_counts ──────────────────────────────────────────────────

    #[test]
    fn live_turn_counts_zero_when_empty() {
        assert_eq!(live_turn_counts(&[]), TokenCounts::default());
    }

    #[test]
    fn live_turn_counts_zero_when_no_llm_response_since_user_msg() {
        let evs = vec![user_msg("hi")];
        assert_eq!(live_turn_counts(&evs), TokenCounts::default());
    }

    #[test]
    fn live_turn_counts_accumulates_responses_since_last_user_msg() {
        let evs = vec![
            user_msg("first"),
            llm_response(100, 0, 0, 50), // should be ignored
            turn_end(100, 0, 0, 50),
            user_msg("second"),
            llm_response(30, 5, 2, 10),
            llm_response(40, 0, 8, 15),
        ];
        let c = live_turn_counts(&evs);
        assert_eq!(c.fresh_in, 70);
        assert_eq!(c.cache_write_in, 5);
        assert_eq!(c.cache_read_in, 10);
        assert_eq!(c.out, 25);
    }

    #[test]
    fn live_turn_counts_includes_events_before_first_user_msg_when_no_user_msg() {
        // If there's no UserMessage at all, all events are included.
        let evs = vec![llm_response(10, 0, 0, 5)];
        let c = live_turn_counts(&evs);
        assert_eq!(c.fresh_in, 10);
        assert_eq!(c.out, 5);
    }

    #[test]
    fn live_turn_counts_ignores_non_llm_response_events() {
        let evs = vec![
            user_msg("hi"),
            turn_end(99, 0, 0, 99), // not an LlmResponse — ignored
            llm_response(20, 0, 0, 8),
        ];
        let c = live_turn_counts(&evs);
        assert_eq!(c.fresh_in, 20);
        assert_eq!(c.out, 8);
    }

    // ── session_counts ────────────────────────────────────────────────────

    #[test]
    fn session_counts_zero_when_empty() {
        assert_eq!(session_counts(&[]), TokenCounts::default());
    }

    #[test]
    fn session_counts_sums_all_turn_ends() {
        let evs = vec![
            user_msg("a"),
            llm_response(5, 0, 0, 2),
            turn_end(10, 2, 1, 4),
            user_msg("b"),
            llm_response(8, 0, 0, 3),
            turn_end(15, 0, 3, 6),
        ];
        let c = session_counts(&evs);
        assert_eq!(c.fresh_in, 25);
        assert_eq!(c.cache_write_in, 2);
        assert_eq!(c.cache_read_in, 4);
        assert_eq!(c.out, 10);
    }

    #[test]
    fn session_counts_ignores_non_turn_end_events() {
        let evs = vec![
            user_msg("hi"),
            llm_response(100, 50, 20, 40),
        ];
        assert_eq!(session_counts(&evs), TokenCounts::default());
    }

    // ── TokenCounts::add ──────────────────────────────────────────────────

    #[test]
    fn token_counts_add_sums_all_fields() {
        let a = TokenCounts { fresh_in: 1, cache_write_in: 2, cache_read_in: 3, out: 4 };
        let b = TokenCounts { fresh_in: 10, cache_write_in: 20, cache_read_in: 30, out: 40 };
        let sum = a.add(b);
        assert_eq!(sum, TokenCounts { fresh_in: 11, cache_write_in: 22, cache_read_in: 33, out: 44 });
    }

    #[test]
    fn token_counts_add_with_zero_is_identity() {
        let a = TokenCounts { fresh_in: 5, cache_write_in: 3, cache_read_in: 1, out: 7 };
        assert_eq!(a.add(TokenCounts::default()), a);
        assert_eq!(TokenCounts::default().add(a), a);
    }
}
