/**
 * Application state — flat ServerMessage[] state model.
 *
 * The primary data structure is a flat `events: ServerMessage[]` array that
 * mirrors the structure of events.jsonl. Turn grouping is a *rendering
 * concern*, derived by `computeRenderGroups()` at render time rather than
 * baked into the state shape. This means events that don't belong to any turn
 * (session_started, server_started, server_stopped, future inter-turn events)
 * are naturally first-class citizens — they just sit in the flat array where
 * they belong.
 *
 * Ephemeral streaming signals (text/thinking fragments) are never persisted
 * and never pushed into `events`; they accumulate in `streamingText` /
 * `streamingThinking` and are cleared when the settled `llm_response` arrives.
 */

import { batch } from "solid-js";
import { createStore, produce } from "solid-js/store";
import type { ServerMessage } from "../protocol";
import { now } from "../../iso-timestamp.js";

// ---------------------------------------------------------------------------
// Render groups — derived from the flat event list at render time
// ---------------------------------------------------------------------------

/**
 * A render group is either:
 *  - "free": events not belonging to any turn (pre-first-turn, inter-turn, or
 *    post-last-turn). These render as standalone blocks in the feed.
 *  - "turn": a user-initiated turn, starting with user_message, optionally
 *    ending with turn_end or turn_interrupted.
 */
export type RenderGroup =
  | { kind: "free"; events: ServerMessage[] }
  | { kind: "turn"; events: ServerMessage[]; done: boolean };

/**
 * Derive render groups from a flat event list.
 *
 * Events before the first user_message, and between turns (after turn_end /
 * turn_interrupted and before the next user_message), form "free" groups.
 * Each user_message starts a new "turn" group.
 */
export function computeRenderGroups(events: ServerMessage[]): RenderGroup[] {
  const groups: RenderGroup[] = [];
  let currentTurnIdx = -1; // index into groups[] of the active turn group
  let freeEvents: ServerMessage[] = [];

  const flushFree = () => {
    if (freeEvents.length > 0) {
      groups.push({ kind: "free", events: freeEvents });
      freeEvents = [];
    }
  };

  for (const e of events) {
    if (e.type === "user_message") {
      flushFree();
      groups.push({ kind: "turn", events: [e], done: false });
      currentTurnIdx = groups.length - 1;
    } else if (currentTurnIdx >= 0) {
      const g = groups[currentTurnIdx] as Extract<RenderGroup, { kind: "turn" }>;
      g.events.push(e);
      if (e.type === "turn_end" || e.type === "turn_interrupted") {
        g.done = true;
        currentTurnIdx = -1; // subsequent events are free until the next user_message
      }
    } else {
      // No active turn: collect as a free event
      freeEvents.push(e);
    }
  }

  flushFree();
  return groups;
}

// ---------------------------------------------------------------------------
// Metrics and duration types
// ---------------------------------------------------------------------------

/** Aggregated metrics shown in the sticky footer bar. */
export interface StickyMetrics {
  /** Tokens processed fresh — does NOT include cache hits or cache writes. */
  freshInTokens: number;
  /** Tokens written into the prompt cache this call. */
  writeInTokens: number;
  /** Tokens retrieved from the prompt cache (not reprocessed). */
  readInTokens: number;
  /** Tokens generated by the model. */
  outTokens: number;
  /** Sum of requestBytes across all llm_call events in this scope. */
  requestBytes: number;
}

/**
 * Duration metrics derived from event timestamps — never from wall-clock.
 */
export interface DurationMetrics {
  llmMs: number;
  toolMs: number;
  turnMs: number;
}

export const zeroDurations = (): DurationMetrics => ({ llmMs: 0, toolMs: 0, turnMs: 0 });

/** Shape of the last completed turn_end event, for the per-turn sticky row. */
interface LastTurnInfo {
  metrics: StickyMetrics;
  durations: DurationMetrics;
  model: string;
}

interface AppState {
  /** Socket is open but server has not yet sent the post-history "ready" signal. */
  connecting: boolean;
  connected: boolean;
  streaming: boolean;
  /** True while an llm_retry backoff is in progress (clears on llm_response / turn end). */
  retrying: boolean;
  /** Flat event log — mirrors events.jsonl. Primary source of truth for the UI. */
  events: ServerMessage[];
  /** Ephemeral accumulated streaming text (not in events; cleared on llm_response). */
  streamingText: string;
  /** Ephemeral accumulated streaming thinking (not in events; cleared on llm_response). */
  streamingThinking: string;
  /** Number of consecutive failed reconnect attempts (reset on successful connect) */
  retryCount: number;
  /** Metrics from the most recently completed turn (null if no turn finished yet). */
  lastTurnEnd: LastTurnInfo | null;
  /** Cumulative token metrics across all completed turns in the session. */
  sessionTotals: StickyMetrics;
  /** Cumulative duration metrics across all completed turns in the session. */
  sessionDurations: DurationMetrics;
  /** Cumulative metrics from all compaction LLM calls in the session. */
  compactionTotals: StickyMetrics;
  /** Live accumulation of the current in-progress turn (reset on user_message, updated on llm_response). */
  liveTurn: StickyMetrics | null;
  /**
   * Live duration accumulation for the current in-progress turn.
   */
  liveDurations: DurationMetrics;
  /** User's chosen model (set from session_started, model_changed, session_info). */
  liveModel: string;
  /** Current thinking effort level (set by session_info and effort_changed events). */
  liveEffort: string;
  /** Session directory path for the current session (set by session_info from server). */
  sessionDir: string;
  /** Display name for the current session (set by session_info / session_renamed). */
  sessionName: string;
  /** Working directory Omega was launched from (set by session_info from server). */
  cwd: string;
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

export const zeroMetrics = (): StickyMetrics => ({
  freshInTokens: 0, writeInTokens: 0, readInTokens: 0, outTokens: 0, requestBytes: 0,
});

const [state, setState] = createStore<AppState>({
  connecting: false,
  connected: false,
  streaming: false,
  retrying: false,
  events: [],
  streamingText: "",
  streamingThinking: "",
  retryCount: 0,
  lastTurnEnd: null,
  sessionTotals: zeroMetrics(),
  sessionDurations: zeroDurations(),
  compactionTotals: zeroMetrics(),
  liveTurn: null,
  liveDurations: zeroDurations(),
  liveModel: "",
  liveEffort: "medium",
  sessionDir: "",
  sessionName: "",
  cwd: "",
});

export { state };

/** Extract a StickyMetrics snapshot from a turn_end event's metrics field.
 *  requestBytes is not in turn_end — pass it in separately (summed from llm_call events). */
function metricsFromTurnEnd(e: ServerMessage & { type: "turn_end" }, requestBytes: number): StickyMetrics {
  const m = e.metrics;
  return {
    freshInTokens:  m.inputTokens,
    writeInTokens:  m.cacheCreationTokens ?? 0,
    readInTokens:   m.cacheReadTokens ?? 0,
    outTokens:      m.outputTokens,
    requestBytes,
  };
}

/** Sum requestBytes from all llm_call events in an event list. */
function sumRequestBytes(events: ServerMessage[]): number {
  let total = 0;
  for (const e of events) {
    if (e.type === "llm_call") total += e.requestBytes ?? 0;
  }
  return total;
}

/** Add two StickyMetrics together (for cumulative session totals). */
function addMetrics(a: StickyMetrics, b: StickyMetrics): StickyMetrics {
  return {
    freshInTokens:  a.freshInTokens  + b.freshInTokens,
    writeInTokens:  a.writeInTokens  + b.writeInTokens,
    readInTokens:   a.readInTokens   + b.readInTokens,
    outTokens:      a.outTokens      + b.outTokens,
    requestBytes:   a.requestBytes   + b.requestBytes,
  };
}

function addDurations(a: DurationMetrics, b: DurationMetrics): DurationMetrics {
  return {
    llmMs:  a.llmMs  + b.llmMs,
    toolMs: a.toolMs + b.toolMs,
    turnMs: a.turnMs + b.turnMs,
  };
}

/**
 * Parse an ISO timestamp string to milliseconds-since-epoch.
 * Returns NaN if absent or unparseable (callers must guard).
 */
function tsMs(time: string | undefined): number {
  if (!time) return NaN;
  return new Date(time).getTime();
}

/**
 * Find the index of the most recent user_message in an event list.
 * Returns 0 as a fallback if none found.
 */
function findCurrentTurnStart(events: ServerMessage[]): number {
  for (let i = events.length - 1; i >= 0; i--) {
    if (events[i]!.type === "user_message") return i;
  }
  return 0;
}

// ---------------------------------------------------------------------------
// Duration computation helpers (operate on event slices)
// ---------------------------------------------------------------------------

/**
 * Compute DurationMetrics by walking a completed turn's event list.
 *
 * Safe for replay: uses only .time fields from persisted events, never Date.now().
 */
export function computeDurations(events: ServerMessage[]): DurationMetrics {
  let llmMs = 0;
  let toolMs = 0;
  let turnMs = 0;

  let pendingLlmCallTs: number | null = null;
  let inToolBatch = false;
  let batchMinCallTs = Infinity;
  let batchMaxResultTs = -Infinity;
  let batchHasCall = false;
  let batchHasResult = false;

  let userMessageTs: number | null = null;

  for (const e of events) {
    switch (e.type) {
      case "user_message":
        userMessageTs = tsMs(e.time);
        break;

      case "llm_call": {
        if (inToolBatch && batchHasCall && batchHasResult) {
          const span = batchMaxResultTs - batchMinCallTs;
          if (span > 0) toolMs += span;
        }
        inToolBatch = false;
        batchHasCall = false;
        batchHasResult = false;
        batchMinCallTs = Infinity;
        batchMaxResultTs = -Infinity;

        pendingLlmCallTs = tsMs(e.time);
        break;
      }

      case "llm_response": {
        if (pendingLlmCallTs !== null) {
          const respTs = tsMs(e.time);
          if (!isNaN(respTs) && !isNaN(pendingLlmCallTs)) {
            llmMs += respTs - pendingLlmCallTs;
          }
          pendingLlmCallTs = null;
        }
        inToolBatch = true;
        batchHasCall = false;
        batchHasResult = false;
        batchMinCallTs = Infinity;
        batchMaxResultTs = -Infinity;
        break;
      }

      case "tool_call": {
        if (inToolBatch) {
          const t = tsMs(e.time);
          if (!isNaN(t)) {
            batchHasCall = true;
            if (t < batchMinCallTs) batchMinCallTs = t;
          }
        }
        break;
      }

      case "tool_result": {
        if (inToolBatch) {
          const t = tsMs(e.time);
          if (!isNaN(t)) {
            batchHasResult = true;
            if (t > batchMaxResultTs) batchMaxResultTs = t;
          }
        }
        break;
      }

      case "turn_end": {
        if (inToolBatch && batchHasCall && batchHasResult) {
          const span = batchMaxResultTs - batchMinCallTs;
          if (span > 0) toolMs += span;
        }
        inToolBatch = false;

        if (userMessageTs !== null) {
          const endTs = tsMs(e.time);
          if (!isNaN(endTs) && !isNaN(userMessageTs)) {
            turnMs = endTs - userMessageTs;
          }
        }
        break;
      }

      default:
        break;
    }
  }

  return { llmMs, toolMs, turnMs };
}

/**
 * Compute live (in-progress) duration metrics from a partial turn's event list.
 */
export function computeLiveDurations(events: ServerMessage[]): DurationMetrics {
  let llmMs = 0;
  let toolMs = 0;

  let pendingLlmCallTs: number | null = null;
  let inToolBatch = false;
  let batchMinCallTs = Infinity;
  let batchMaxResultTs = -Infinity;
  const batchCallIds = new Set<string>();
  const batchResultIds = new Set<string>();

  for (const e of events) {
    switch (e.type) {
      case "llm_call": {
        if (inToolBatch && batchCallIds.size > 0 && batchCallIds.size === batchResultIds.size) {
          const span = batchMaxResultTs - batchMinCallTs;
          if (span > 0) toolMs += span;
        }
        inToolBatch = false;
        batchCallIds.clear();
        batchResultIds.clear();
        batchMinCallTs = Infinity;
        batchMaxResultTs = -Infinity;

        pendingLlmCallTs = tsMs(e.time);
        break;
      }

      case "llm_response": {
        if (pendingLlmCallTs !== null) {
          const respTs = tsMs(e.time);
          if (!isNaN(respTs) && !isNaN(pendingLlmCallTs)) {
            llmMs += respTs - pendingLlmCallTs;
          }
          pendingLlmCallTs = null;
        }
        inToolBatch = true;
        batchCallIds.clear();
        batchResultIds.clear();
        batchMinCallTs = Infinity;
        batchMaxResultTs = -Infinity;
        break;
      }

      case "tool_call": {
        if (inToolBatch) {
          batchCallIds.add(e.id);
          const t = tsMs(e.time);
          if (!isNaN(t) && t < batchMinCallTs) batchMinCallTs = t;
        }
        break;
      }

      case "tool_result": {
        if (inToolBatch) {
          batchResultIds.add(e.id);
          const t = tsMs(e.time);
          if (!isNaN(t) && t > batchMaxResultTs) batchMaxResultTs = t;

          if (batchCallIds.size > 0 && batchCallIds.size === batchResultIds.size) {
            const span = batchMaxResultTs - batchMinCallTs;
            if (span > 0) toolMs += span;
            batchCallIds.clear();
            batchResultIds.clear();
            batchMinCallTs = Infinity;
            batchMaxResultTs = -Infinity;
          }
        }
        break;
      }

      default:
        break;
    }
  }

  return { llmMs, toolMs, turnMs: 0 };
}

// ---------------------------------------------------------------------------
// State update functions
// ---------------------------------------------------------------------------

/**
 * Call from ws.onopen. Sets the connecting state (socket open, awaiting
 * history from server). Not a server message — the connection is not yet
 * ready when onopen fires.
 */
export function setConnecting(): void {
  setState("connecting", true);
  setState("connected", false);
}

/**
 * Call from ws.onclose. Not a server message — the connection is already
 * gone when onclose fires.
 */
export function handleDisconnect(): void {
  setState("connecting", false);
  setState("connected", false);
  setState("streaming", false);
  setState("retryCount", r => r + 1);
}

export function dispatch(event: ServerMessage): void {
  switch (event.type) {
    case "ready":
      setState("connecting", false);
      setState("connected", true);
      setState("streaming", false);
      setState("retryCount", 0);
      break;

    case "history": {
      // Rebuild all state from the flat event log sent by the server.
      // The server runs closeOpenTurn() before sending, so any open turn
      // already has a synthetic turn_interrupted appended.
      const rawEvents = event.events;

      let replayLastTurnEnd: LastTurnInfo | null = null;
      let replaySessionTotals: StickyMetrics = zeroMetrics();
      let replaySessionDurations: DurationMetrics = zeroDurations();
      let replayCompactionTotals: StickyMetrics = zeroMetrics();
      let replayLiveModel = "";
      let replayLiveEffort = "medium";
      let replayLiveDurations: DurationMetrics = zeroDurations();
      let replayStreaming = false;

      // Scan events to derive session-level aggregates.
      // We process turn slices to compute per-turn metrics.
      let currentTurnStartIdx = -1;

      for (let i = 0; i < rawEvents.length; i++) {
        const e = rawEvents[i]!;

        if (e.type === "session_started") {
          replayLiveModel = e.model;
          replayLiveEffort = e.effort;
        }

        if (e.type === "model_changed") {
          replayLiveModel = e.model;
        }

        if (e.type === "effort_changed") {
          replayLiveEffort = e.effort;
        }

        // Note: llm_call.model is NOT used for replayLiveModel — internal
        // calls (e.g. resumption) may use a different model than the user's
        // chosen one. model_changed and session_started are authoritative.

        if (e.type === "user_message") {
          currentTurnStartIdx = i;
          replayStreaming = true;
        }

        if (e.type === "turn_end" && currentTurnStartIdx >= 0) {
          const turnEvents = rawEvents.slice(currentTurnStartIdx, i + 1);
          const sm = metricsFromTurnEnd(e, sumRequestBytes(turnEvents));
          const sd = computeDurations(turnEvents);
          replayLastTurnEnd = {
            metrics: sm,
            durations: sd,
            model: replayLiveModel,
          };
          replaySessionTotals = addMetrics(replaySessionTotals, sm);
          replaySessionDurations = addDurations(replaySessionDurations, sd);
          replayStreaming = false;
          currentTurnStartIdx = -1;
        }

        if (e.type === "turn_interrupted") {
          replayStreaming = false;
          currentTurnStartIdx = -1;
        }

        // Note: compacted handling could go here if needed for replayCompactionTotals
      }

      // Secondary crash recovery: if still marked streaming after all events,
      // the server didn't close the turn (defensive). Append a synthetic
      // turn_interrupted so the UI is never left stuck in streaming state.
      const replayEvents: ServerMessage[] = replayStreaming && currentTurnStartIdx >= 0
        ? [...rawEvents, { type: "turn_interrupted" as const, time: now() }]
        : rawEvents;

      if (replayStreaming && currentTurnStartIdx >= 0) {
        const partialTurnEvents = replayEvents.slice(currentTurnStartIdx);
        replayLiveDurations = computeLiveDurations(partialTurnEvents);
      }

      // Single batch write — SolidJS sees one atomic state transition.
      batch(() => {
        setState("events", replayEvents);
        setState("streamingText", "");
        setState("streamingThinking", "");
        setState("streaming", false);
        setState("connected", true);
        setState("retryCount", 0);
        setState("lastTurnEnd", replayLastTurnEnd);
        setState("sessionTotals", replaySessionTotals);
        setState("sessionDurations", replaySessionDurations);
        setState("compactionTotals", replayCompactionTotals);
        setState("liveDurations", replayLiveDurations);
        setState("liveModel", replayLiveModel);
        setState("liveEffort", replayLiveEffort);
      });
      break;
    }

    case "session_info":
      setState("sessionDir", event.dir);
      setState("sessionName", event.name ?? "");
      setState("liveModel", event.model);
      setState("liveEffort", event.effort);
      setState("cwd", event.cwd);
      break;

    case "reset_done":
      // Server has created a new agent — clear all UI state
      setState("events", []);
      setState("streamingText", "");
      setState("streamingThinking", "");
      setState("streaming", false);
      setState("retrying", false);
      setState("lastTurnEnd", null);
      setState("sessionTotals", zeroMetrics());
      setState("sessionDurations", zeroDurations());
      setState("compactionTotals", zeroMetrics());
      setState("liveTurn", null);
      setState("liveDurations", zeroDurations());
      setState("liveModel", "");
      setState("liveEffort", "medium");
      setState("sessionName", "");
      break;

    case "user_message":
      setState(produce(s => {
        // Clear any leftover streaming content from a previous turn that ended
        // without an llm_response (edge case). This prevents abandoned text
        // from showing in the new turn's streaming slot.
        s.streamingText = "";
        s.streamingThinking = "";
        s.events.push(event);
      }));
      setState("streaming", true);
      setState("liveTurn", zeroMetrics());
      setState("liveDurations", zeroDurations());
      break;

    case "text":
      // Accumulate streaming text fragments into the ephemeral streamingText slot.
      // Cleared when llm_response arrives (which carries the settled text as its own field).
      setState("streamingText", t => t + event.text);
      break;

    case "thinking":
      // Accumulate streaming thinking fragments.
      // Cleared when llm_response arrives.
      setState("streamingThinking", t => t + event.text);
      break;

    case "turn_end": {
      setState(produce(s => { s.events.push(event); }));
      setState("streaming", false);
      setState("retrying", false);
      // Compute durations and metrics from the current turn's events
      const allEvents = state.events;
      const turnStart = findCurrentTurnStart(allEvents);
      const currentTurnEvents = allEvents.slice(turnStart);
      const sd = computeDurations(currentTurnEvents);
      const sm = metricsFromTurnEnd(event, sumRequestBytes(currentTurnEvents));
      setState("lastTurnEnd", { metrics: sm, durations: sd, model: state.liveModel });
      setState("sessionTotals", prev => addMetrics(prev, sm));
      setState("sessionDurations", prev => addDurations(prev, sd));
      setState("liveTurn", null);
      setState("liveDurations", zeroDurations());
      break;
    }

    case "turn_interrupted":
      setState(produce(s => { s.events.push(event); }));
      setState("streaming", false);
      setState("retrying", false);
      setState("liveTurn", null);
      setState("liveDurations", zeroDurations());
      break;

    case "llm_response": {
      setState(produce(s => {
        s.streamingText = "";
        s.streamingThinking = "";
        s.events.push(event);
      }));
      setState("retrying", false);
      // Recompute live durations from the current turn's events (llmMs ticks up)
      const allEventsAfterResp = state.events;
      const turnStartAfterResp = findCurrentTurnStart(allEventsAfterResp);
      setState("liveDurations", computeLiveDurations(allEventsAfterResp.slice(turnStartAfterResp)));
      // Accumulate live per-turn token totals
      const u = event.usage;
      setState("liveTurn", prev => {
        if (!prev) return prev;
        return {
          freshInTokens:  prev.freshInTokens  + u.input_tokens,
          writeInTokens:  prev.writeInTokens  + (u.cache_creation_input_tokens ?? 0),
          readInTokens:   prev.readInTokens   + (u.cache_read_input_tokens ?? 0),
          outTokens:      prev.outTokens      + u.output_tokens,
          requestBytes:   prev.requestBytes,
        };
      });
      break;
    }

    case "session_started": {
      setState(produce(s => { s.events.push(event); }));
      setState("liveModel", event.model);
      if ((event as any).effort) setState("liveEffort", (event as any).effort);
      break;
    }

    case "llm_call": {
      setState(produce(s => { s.events.push(event); }));
      // Tick up requestBytes in the live turn accumulator
      setState("liveTurn", prev => {
        if (!prev) return prev;
        return { ...prev, requestBytes: prev.requestBytes + (event.requestBytes ?? 0) };
      });
      break;
    }

    case "tool_result": {
      setState(produce(s => { s.events.push(event); }));
      // Recompute live durations (toolMs may tick up when last result of batch arrives)
      const allEventsAfterResult = state.events;
      const turnStartAfterResult = findCurrentTurnStart(allEventsAfterResult);
      setState("liveDurations", computeLiveDurations(allEventsAfterResult.slice(turnStartAfterResult)));
      break;
    }

    case "llm_retry":
      setState(produce(s => {
        s.events.push(event);
        // Clear any partial streaming content accumulated before the error.
        // Without this, the user sees a frozen thinking/text block with a
        // blinking cursor and no indication that a retry is in progress.
        // Fresh content will start accumulating again when the retry fires.
        s.streamingText = "";
        s.streamingThinking = "";
      }));
      setState("retrying", true);
      break;

    case "effort_changed":
      setState(produce(s => { s.events.push(event); }));
      setState("liveEffort", event.effort);
      break;

    case "model_changed":
      setState(produce(s => { s.events.push(event); }));
      setState("liveModel", event.model);
      break;

    case "resuming_session":
      setState(produce(s => { s.events.push(event); }));
      // Resumption streams an LLM call — lock the UI the same way a turn does.
      // The subsequent "ready" event (sent after session_resumed) clears it.
      setState("streaming", true);
      break;

    case "server_started":
    case "server_stopped":
    case "tool_call":
    case "compacted":
    case "llm_error":
    case "agent_error":
    case "transport_error":
    case "session_resumed":
      setState(produce(s => { s.events.push(event); }));
      break;

    case "session_renamed":
      // Update the display name if it refers to the current session.
      // Relative dir comparison: state.sessionDir ends with the folder name.
      if (state.sessionDir.endsWith("/" + event.sessionDir) || state.sessionDir === event.sessionDir) {
        setState("sessionName", event.name);
      }
      break;

    // Protocol envelopes handled elsewhere — no state update needed
    case "session_deleted":
      break;
  }
}
