/**
 * Application store — Turn[] state model.
 *
 * All UI rendering derives from this reactive store.
 * Each Turn holds an ordered list of AgentEvent-shaped objects
 * received over the WebSocket.
 */

import { batch } from "solid-js";
import { createStore, produce } from "solid-js/store";

// ---------------------------------------------------------------------------
// Types mirroring src/agent.ts AgentEvent (subset we care about for display)
// ---------------------------------------------------------------------------

export type WsEvent =
  | { type: "connected" }
  | { type: "disconnected" }
  | { type: "history"; events: WsEvent[] }
  | { type: "auth"; mode: string }
  | { type: "reset_done" }
  | { type: "session_info"; dir: string }
  | { type: "user_message"; ts?: string; content: string }
  | { type: "text"; text: string }
  | { type: "assistant_text"; ts?: string; text: string }
  // OmegaEvent variants (persisted names are authoritative — see plan/dev-policy.md)
  | { type: "session_start"; ts?: string; authMode: string; model: string; provider: string; systemPrompt: string }
  | { type: "session_end"; ts?: string; outcome: "clean" | "error"; reason?: string }
  | { type: "tool_call"; ts?: string; id: string; name: string; input: unknown }
  | { type: "tool_result"; ts?: string; id: string; name: string; isError: boolean; durationMs: number; output: string }
  | { type: "llm_response"; ts?: string; provider: string; url: string; stopReason: string; usage: { input_tokens: number; output_tokens: number; cache_creation_input_tokens?: number | null; cache_read_input_tokens?: number | null; service_tier?: string | null }; content?: unknown[]; raw?: unknown }
  | { type: "llm_call"; ts?: string; provider: string; url: string; model: string; contextHashes: string[]; cacheBreakpointIndex: number | null; request?: unknown }
  | { type: "llm_retry"; ts?: string; attempt: number; provider: string; waitMs: number; error: string }
  | { type: "model_changed"; ts?: string; provider: string; model: string }
  | { type: "oauth_token_expired"; ts?: string; attempt: number; httpStatus?: number }
  | { type: "oauth_refreshed"; ts?: string }
  | { type: "compact_user_start"; ts?: string }
  | { type: "compact_user_done"; ts?: string; messagesBefore: number; messagesAfter: number; usage?: { input_tokens: number; output_tokens: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number } }
  | { type: "compact_user_error"; ts?: string; error: string }
  | { type: "compact_auto_start"; ts?: string; messagesBefore: number }
  | { type: "compact_auto_done"; ts?: string; messagesBefore: number; messagesAfter: number; usage?: { input_tokens: number; output_tokens: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number } }
  | { type: "compact_auto_error"; ts?: string; error: string }
  | { type: "world_state_saved"; ts?: string; path: string; charCount: number }
  | { type: "turn_end"; ts?: string; metrics: { inputTokens: number; outputTokens: number; costUsd: number; savedUsd?: number; ttftMs: number | null; totalMs?: number; cacheCreationTokens?: number; cacheReadTokens?: number }; model: string; provider: string }
  | { type: "llm_error"; ts?: string; provider: string; error: string }
  | { type: "agent_error"; ts?: string; error: string }
  | { type: "error"; ts?: string; error: string }
  | { type: "turn_interrupted"; ts?: string };

export interface Turn {
  id: number;
  events: WsEvent[];
  done: boolean;
}

// ---------------------------------------------------------------------------

/** Aggregated metrics shown in the sticky footer bar. */
export interface StickyMetrics {
  /** Tokens processed fresh — does NOT include cache hits or cache writes. */
  freshInTokens: number;
  /** Tokens written into the prompt cache this call. */
  writeInTokens: number;
  /** Tokens retrieved from the prompt cache (not reprocessed). */
  readInTokens: number;
  /** Tokens generated by the model. */
  outTokens: number;
}

/** Shape of the last completed turn_end event, for the per-turn sticky row. */
interface LastTurnInfo {
  metrics: StickyMetrics;
  model: string;
  provider: string;
}

interface AppState {
  connected: boolean;
  streaming: boolean;
  authMode: string;
  turns: Turn[];
  /** Number of consecutive failed reconnect attempts (reset on successful connect) */
  retryCount: number;
  /** Metrics from the most recently completed turn (null if no turn finished yet). */
  lastTurnEnd: LastTurnInfo | null;
  /** Cumulative metrics across all completed turns in the session. */
  sessionTotals: StickyMetrics;
  /** Cumulative metrics from all compaction LLM calls in the session. */
  compactionTotals: StickyMetrics;
  /** Live accumulation of the current in-progress turn (reset on user_message, updated on llm_response). */
  liveTurn: StickyMetrics | null;
  /** Provider for the current/last turn (set from llm_response, used for live bar display). */
  liveProvider: string;
  /** Model for the current/last turn (set from llm_response, used for live bar display). */
  liveModel: string;

  /** Session directory path for the current session (set by session_info from server). */
  sessionDir: string;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const zeroMetrics = (): StickyMetrics => ({
  freshInTokens: 0, writeInTokens: 0, readInTokens: 0, outTokens: 0,
});

const [state, setState] = createStore<AppState>({
  connected: false,
  streaming: false,
  authMode: "",
  turns: [],
  retryCount: 0,
  lastTurnEnd: null,
  sessionTotals: zeroMetrics(),
  compactionTotals: zeroMetrics(),
  liveTurn: null,
  liveProvider: "",
  liveModel: "",
  sessionDir: "",
});

export { state };

let nextTurnId = 0;

function currentTurn(): Turn | undefined {
  return state.turns[state.turns.length - 1];
}

function appendEvent(event: WsEvent): void {
  setState(produce(s => {
    const turn = s.turns[s.turns.length - 1];
    if (turn) turn.events.push(event);
  }));
}

/** Extract a StickyMetrics snapshot from a turn_end event's metrics field. */
function metricsFromTurnEnd(e: WsEvent & { type: "turn_end" }): StickyMetrics {
  const m = e.metrics;
  return {
    freshInTokens:  m.inputTokens,
    writeInTokens:  m.cacheCreationTokens ?? 0,
    readInTokens:   m.cacheReadTokens ?? 0,
    outTokens:      m.outputTokens,
  };
}

/** Add two StickyMetrics together (for cumulative session totals). */
function addMetrics(a: StickyMetrics, b: StickyMetrics): StickyMetrics {
  return {
    freshInTokens:  a.freshInTokens  + b.freshInTokens,
    writeInTokens:  a.writeInTokens  + b.writeInTokens,
    readInTokens:   a.readInTokens   + b.readInTokens,
    outTokens:      a.outTokens      + b.outTokens,
  };
}

export function dispatch(event: WsEvent): void {
  switch (event.type) {
    case "connected":
      setState("connected", true);
      setState("streaming", false);
      setState("retryCount", 0);
      break;

    case "disconnected":
      setState("connected", false);
      setState("streaming", false);
      setState("retryCount", r => r + 1);
      break;

    case "history": {
      // Rebuild turns from the event log using plain JS objects, then set the
      // final result in one store write.  Previous approach dispatched each
      // event individually inside batch(), mixing array replacement with
      // produce-based mutation — this confused SolidJS's fine-grained change
      // tracking and left <For> with a stale reference after a page reload.
      const turns: Turn[] = [];
      let streaming = false;
      let tid = 0;
      let replayLastTurnEnd: LastTurnInfo | null = null;
      let replaySessionTotals: StickyMetrics = zeroMetrics();
      let replayCompactionTotals: StickyMetrics = zeroMetrics();

      for (const e of event.events) {
        const cur = () => turns[turns.length - 1];

        switch (e.type) {
          case "user_message":
            turns.push({ id: tid++, events: [e], done: false });
            streaming = true;
            break;

          case "assistant_text": {
            // Replay path: no live `text` fragments — push the full text as a rendered block.
            const t = cur();
            if (t) t.events.push({ type: "text", text: (e as any).text });
            break;
          }

          case "turn_end": {
            const t = cur();
            if (t) {
              t.events.push(e);
              t.done = true;
            }
            streaming = false;
            // Accumulate sticky metrics
            const sm = metricsFromTurnEnd(e);
            replayLastTurnEnd = { metrics: sm, model: e.model, provider: e.provider };
            replaySessionTotals = addMetrics(replaySessionTotals, sm);
            break;
          }

          case "turn_interrupted": {
            const t = cur();
            if (t) {
              t.events.push(e);
              t.done = true;
            }
            streaming = false;
            break;
          }

          case "compact_auto_done":
          case "compact_user_done": {
            const u = (e as any).usage;
            if (u) replayCompactionTotals = addMetrics(replayCompactionTotals, {
              freshInTokens: u.input_tokens ?? 0,
              writeInTokens: u.cache_creation_input_tokens ?? 0,
              readInTokens:  u.cache_read_input_tokens ?? 0,
              outTokens:     u.output_tokens ?? 0,
            });
            const t = cur();
            if (t) t.events.push(e);
            break;
          }

          // Transport-only events — never appear in persisted history,
          // but listed for completeness (server filters them out).
          case "connected":
          case "disconnected":
          case "history":
          case "auth":
          case "reset_done":
          case "session_info":
            break;

          // All other events: append to the current turn's event list.
          default: {
            const t = cur();
            if (t) t.events.push(e);
            break;
          }
        }
      }

      // Close any open turn (server crashed mid-turn, no turn_end emitted).
      if (streaming) {
        const t = turns[turns.length - 1];
        if (t) {
          t.events.push({ type: "turn_interrupted" });
          t.done = true;
        }
        streaming = false;
      }

      nextTurnId = tid;
      // Single batch write — SolidJS sees one atomic state transition.
      batch(() => {
        setState("turns", turns);
        setState("authMode", "");
        setState("streaming", false);
        setState("connected", true);
        setState("retryCount", 0);
        setState("lastTurnEnd", replayLastTurnEnd);
        setState("sessionTotals", replaySessionTotals);
        setState("compactionTotals", replayCompactionTotals);
      });
      break;
    }

    case "auth":
      setState("authMode", event.mode);
      break;

    case "session_info":
      setState("sessionDir", event.dir);
      break;

    case "reset_done":
      // Server has created a new agent — clear all UI state
      setState("turns", []);
      setState("streaming", false);
      setState("lastTurnEnd", null);
      setState("sessionTotals", zeroMetrics());
      setState("compactionTotals", zeroMetrics());
      setState("liveTurn", null);
      setState("liveProvider", "");
      setState("liveModel", "");
      nextTurnId = 0;
      break;

    case "user_message":
      // Start a new turn
      setState("turns", t => [...t, {
        id: nextTurnId++,
        events: [event],
        done: false,
      }]);
      setState("streaming", true);
      setState("liveTurn", zeroMetrics());
      break;

    case "text":
      // Interleave text fragments directly into turn.events.
      // If the last event is already a text block, concatenate into it so
      // SolidJS re-renders just that node (visible character-by-character).
      // If the last event is something else (e.g. a tool_result), push a new
      // text block so the text appears after that event in the correct order.
      setState(produce(s => {
        const turn = s.turns[s.turns.length - 1];
        if (!turn) return;
        const last = turn.events[turn.events.length - 1];
        if (last?.type === "text") {
          (last as { type: "text"; text: string }).text += event.text;
        } else {
          turn.events.push({ type: "text", text: event.text });
        }
      }));
      break;

    case "assistant_text":
      // Persisted full-text event — used during history replay only.
      // During live streaming, text is already accumulated into turn.events
      // from individual `text` fragments, so this is a no-op on the live path.
      // During replay, no `text` fragments were emitted, so push the full text.
      setState(produce(s => {
        const turn = s.turns[s.turns.length - 1];
        if (!turn) return;
        // Live path: the last event in the list will already be a `text` block
        // built from streaming fragments — skip to avoid duplication.
        const hasLiveText = turn.events.some(e => e.type === "text");
        if (!hasLiveText) {
          turn.events.push({ type: "text", text: event.text });
        }
      }));
      break;

    case "turn_end": {
      setState(produce(s => {
        const turn = s.turns[s.turns.length - 1];
        if (turn) {
          turn.events.push(event);
          turn.done = true;
        }
      }));
      // turn_end means the agentic loop finished; clear streaming so replayed
      // history doesn't leave the UI stuck in streaming state.
      setState("streaming", false);
      // Update sticky metrics and clear live accumulator
      const sm = metricsFromTurnEnd(event);
      setState("lastTurnEnd", { metrics: sm, model: event.model, provider: event.provider });
      setState("sessionTotals", prev => addMetrics(prev, sm));
      setState("liveTurn", null);
      break;
    }

    case "turn_interrupted":
      setState(produce(s => {
        const turn = s.turns[s.turns.length - 1];
        if (turn) {
          turn.events.push(event);
          turn.done = true;
        }
      }));
      setState("streaming", false);
      setState("liveTurn", null);
      break;

    case "llm_response": {
      appendEvent(event);
      // Accumulate live per-turn token totals so the metrics bar ticks up mid-turn.
      const u = event.usage;
      setState("liveProvider", event.provider);
      setState("liveModel", event.model);
      setState("liveTurn", prev => {
        if (!prev) return prev;
        return {
          freshInTokens:  prev.freshInTokens  + u.input_tokens,
          writeInTokens:  prev.writeInTokens  + (u.cache_creation_input_tokens ?? 0),
          readInTokens:   prev.readInTokens   + (u.cache_read_input_tokens ?? 0),
          outTokens:      prev.outTokens      + u.output_tokens,
        };
      });
      break;
    }

    case "session_start":
    case "session_end":
    case "tool_call":
    case "tool_result":
    case "llm_call":
    case "llm_retry":
    case "model_changed":
    case "oauth_token_expired":
    case "oauth_refreshed":
    case "compact_auto_done":
    case "compact_user_done": {
      appendEvent(event);
      const u = event.usage;
      if (u) setState("compactionTotals", prev => addMetrics(prev, {
        freshInTokens: u.input_tokens ?? 0,
        writeInTokens: u.cache_creation_input_tokens ?? 0,
        readInTokens:  u.cache_read_input_tokens ?? 0,
        outTokens:     u.output_tokens ?? 0,
      }));
      break;
    }

    case "compact_user_start":
    case "compact_user_error":
    case "compact_auto_start":
    case "compact_auto_error":
    case "world_state_saved":
    case "llm_error":
    case "agent_error":
    case "error":
      appendEvent(event);
      break;
  }
}
