/**
 * Application store — Turn[] state model.
 *
 * All UI rendering derives from this reactive store.
 * Each Turn holds an ordered list of AgentEvent-shaped objects
 * received over the WebSocket.
 */

import { batch } from "solid-js";
import { createStore, produce } from "solid-js/store";

// ---------------------------------------------------------------------------
// Types mirroring src/agent.ts AgentEvent (subset we care about for display)
// ---------------------------------------------------------------------------

export type WsEvent =
  | { type: "connected" }
  | { type: "disconnected" }
  | { type: "history"; events: WsEvent[] }
  | { type: "auth"; mode: string }
  | { type: "reset_done" }
  | { type: "session_info"; dir: string }
  | { type: "user_message"; ts?: string; content: string }
  | { type: "text"; ts?: string; streamingStart?: string; text: string }
  // OmegaEvent variants (persisted names are authoritative — see plan/dev-policy.md)
  | { type: "session_start"; ts?: string; authMode: string; model: string; provider: string; systemPrompt: string }
  | { type: "session_end"; ts?: string; outcome: "clean" | "error"; reason?: string }
  | { type: "tool_call"; ts?: string; id: string; name: string; input: unknown }
  | { type: "tool_result"; ts?: string; id: string; name: string; isError: boolean; durationMs: number; output: string }
  | { type: "llm_response"; ts?: string; stopReason: string; usage: { input_tokens: number; output_tokens: number; cache_creation_input_tokens?: number | null; cache_read_input_tokens?: number | null; service_tier?: string | null }; contextHash: string; text?: string; streamingStart?: string; responseSummary?: Record<string, unknown> }
  | { type: "llm_call"; ts?: string; provider: string; url: string; model: string; contextHashes: string[]; cacheBreakpointIndex: number | null; requestBytes?: number; requestSummary?: Record<string, unknown> }
  | { type: "llm_retry"; ts?: string; attempt: number; provider: string; waitMs: number; error: string }
  | { type: "model_changed"; ts?: string; provider: string; model: string }
  | { type: "oauth_token_expired"; ts?: string; attempt: number; httpStatus?: number }
  | { type: "oauth_refreshed"; ts?: string }
  | { type: "compact_user_start"; ts?: string }
  | { type: "compact_user_done"; ts?: string; messagesBefore: number; messagesAfter: number; usage?: { input_tokens: number; output_tokens: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number } }
  | { type: "compact_user_error"; ts?: string; error: string }
  | { type: "compact_auto_start"; ts?: string; messagesBefore: number }
  | { type: "compact_auto_done"; ts?: string; messagesBefore: number; messagesAfter: number; usage?: { input_tokens: number; output_tokens: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number } }
  | { type: "compact_auto_error"; ts?: string; error: string }
  | { type: "world_state_saved"; ts?: string; path: string; charCount: number }
  | { type: "turn_end"; ts?: string; metrics: { inputTokens: number; outputTokens: number; cacheCreationTokens?: number; cacheReadTokens?: number } }
  | { type: "llm_error"; ts?: string; provider: string; error: string }
  | { type: "agent_error"; ts?: string; error: string }
  | { type: "error"; ts?: string; error: string }
  | { type: "turn_interrupted"; ts?: string };

export interface Turn {
  id: number;
  events: WsEvent[];
  done: boolean;
  /** Accumulated streaming text, shown in a temporary slot during streaming.
   *  Cleared when llm_response arrives; the text is then carried in the llm_response event itself. */
  streamingText?: string;
}

// ---------------------------------------------------------------------------

/** Aggregated metrics shown in the sticky footer bar. */
export interface StickyMetrics {
  /** Tokens processed fresh — does NOT include cache hits or cache writes. */
  freshInTokens: number;
  /** Tokens written into the prompt cache this call. */
  writeInTokens: number;
  /** Tokens retrieved from the prompt cache (not reprocessed). */
  readInTokens: number;
  /** Tokens generated by the model. */
  outTokens: number;
  /** Sum of requestBytes across all llm_call events in this scope. */
  requestBytes: number;
}

/**
 * Duration metrics derived from event timestamps — never from wall-clock.
 * Safe for replay after reconnect because they are recomputed from persisted ts fields.
 *
 * llmMs:  sum of (llm_response.ts − llm_call.ts) per call pair.
 * toolMs: sum of parallel-batch wall spans: (max tool_result.ts − min tool_call.ts)
 *         per batch, where a batch is the group of tool calls between one
 *         llm_response and the next llm_call.
 * turnMs: turn_end.ts − user_message.ts (0 until turn_end arrives).
 */
export interface DurationMetrics {
  llmMs: number;
  toolMs: number;
  turnMs: number;
}

export const zeroDurations = (): DurationMetrics => ({ llmMs: 0, toolMs: 0, turnMs: 0 });

/** Shape of the last completed turn_end event, for the per-turn sticky row. */
interface LastTurnInfo {
  metrics: StickyMetrics;
  durations: DurationMetrics;
  model: string;
  provider: string;
}

interface AppState {
  connected: boolean;
  streaming: boolean;
  authMode: string;
  turns: Turn[];
  /** Number of consecutive failed reconnect attempts (reset on successful connect) */
  retryCount: number;
  /** Metrics from the most recently completed turn (null if no turn finished yet). */
  lastTurnEnd: LastTurnInfo | null;
  /** Cumulative token metrics across all completed turns in the session. */
  sessionTotals: StickyMetrics;
  /** Cumulative duration metrics across all completed turns in the session. */
  sessionDurations: DurationMetrics;
  /** Cumulative metrics from all compaction LLM calls in the session. */
  compactionTotals: StickyMetrics;
  /** Live accumulation of the current in-progress turn (reset on user_message, updated on llm_response). */
  liveTurn: StickyMetrics | null;
  /**
   * Live duration accumulation for the current in-progress turn.
   * llmMs / toolMs tick up as each llm_response / last-tool_result arrives.
   * turnMs stays 0 until turn_end (we never use Date.now() — replay safety).
   */
  liveDurations: DurationMetrics;
  /** Provider for the current/last turn (set from llm_call, used for live bar display). */
  liveProvider: string;
  /** Model for the current/last turn (set from llm_call, used for live bar display). */
  liveModel: string;

  /** Session directory path for the current session (set by session_info from server). */
  sessionDir: string;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const zeroMetrics = (): StickyMetrics => ({
  freshInTokens: 0, writeInTokens: 0, readInTokens: 0, outTokens: 0, requestBytes: 0,
});

const [state, setState] = createStore<AppState>({
  connected: false,
  streaming: false,
  authMode: "",
  turns: [],
  retryCount: 0,
  lastTurnEnd: null,
  sessionTotals: zeroMetrics(),
  sessionDurations: zeroDurations(),
  compactionTotals: zeroMetrics(),
  liveTurn: null,
  liveDurations: zeroDurations(),
  liveProvider: "",
  liveModel: "",
  sessionDir: "",
});

export { state };

let nextTurnId = 0;

function appendEvent(event: WsEvent): void {
  setState(produce(s => {
    const turn = s.turns[s.turns.length - 1];
    if (turn) turn.events.push(event);
  }));
}

/** Extract a StickyMetrics snapshot from a turn_end event's metrics field.
 *  requestBytes is not in turn_end — pass it in separately (summed from llm_call events). */
function metricsFromTurnEnd(e: WsEvent & { type: "turn_end" }, requestBytes: number): StickyMetrics {
  const m = e.metrics;
  return {
    freshInTokens:  m.inputTokens,
    writeInTokens:  m.cacheCreationTokens ?? 0,
    readInTokens:   m.cacheReadTokens ?? 0,
    outTokens:      m.outputTokens,
    requestBytes,
  };
}

/** Sum requestBytes from all llm_call events in an event list. */
function sumRequestBytes(events: WsEvent[]): number {
  let total = 0;
  for (const e of events) {
    if (e.type === "llm_call") total += e.requestBytes ?? 0;
  }
  return total;
}

/** Add two StickyMetrics together (for cumulative session totals). */
function addMetrics(a: StickyMetrics, b: StickyMetrics): StickyMetrics {
  return {
    freshInTokens:  a.freshInTokens  + b.freshInTokens,
    writeInTokens:  a.writeInTokens  + b.writeInTokens,
    readInTokens:   a.readInTokens   + b.readInTokens,
    outTokens:      a.outTokens      + b.outTokens,
    requestBytes:   a.requestBytes   + b.requestBytes,
  };
}

function addDurations(a: DurationMetrics, b: DurationMetrics): DurationMetrics {
  return {
    llmMs:  a.llmMs  + b.llmMs,
    toolMs: a.toolMs + b.toolMs,
    turnMs: a.turnMs + b.turnMs,
  };
}

/**
 * Parse an ISO timestamp string to milliseconds-since-epoch.
 * Returns NaN if absent or unparseable (callers must guard).
 */
function tsMs(ts: string | undefined): number {
  if (!ts) return NaN;
  return new Date(ts).getTime();
}

// ---------------------------------------------------------------------------
// Duration computation helpers
// ---------------------------------------------------------------------------

/**
 * Compute DurationMetrics by walking a completed turn's event list.
 *
 * Safe for replay: uses only .ts fields from persisted events, never Date.now().
 *
 * Algorithm:
 *   - LLM time: each llm_call starts a pending call; when the matching
 *     llm_response arrives, compute the diff and add to llmMs.
 *   - Tool time: between each llm_response and the following llm_call, collect
 *     all tool_call and tool_result timestamps. The batch span is
 *     (max tool_result.ts − min tool_call.ts). Add to toolMs.
 *   - Turn time: turn_end.ts − user_message.ts.
 */
export function computeDurations(events: WsEvent[]): DurationMetrics {
  let llmMs = 0;
  let toolMs = 0;
  let turnMs = 0;

  let pendingLlmCallTs: number | null = null;
  // Tool batch state: between llm_response and next llm_call
  let inToolBatch = false;
  let batchMinCallTs = Infinity;
  let batchMaxResultTs = -Infinity;
  let batchHasCall = false;
  let batchHasResult = false;

  let userMessageTs: number | null = null;

  for (const e of events) {
    switch (e.type) {
      case "user_message":
        userMessageTs = tsMs(e.ts);
        break;

      case "llm_call": {
        // Flush any pending tool batch before the next LLM call starts
        if (inToolBatch && batchHasCall && batchHasResult) {
          const span = batchMaxResultTs - batchMinCallTs;
          if (span > 0) toolMs += span;
        }
        inToolBatch = false;
        batchHasCall = false;
        batchHasResult = false;
        batchMinCallTs = Infinity;
        batchMaxResultTs = -Infinity;

        pendingLlmCallTs = tsMs(e.ts);
        break;
      }

      case "llm_response": {
        if (pendingLlmCallTs !== null) {
          const respTs = tsMs(e.ts);
          if (!isNaN(respTs) && !isNaN(pendingLlmCallTs)) {
            llmMs += respTs - pendingLlmCallTs;
          }
          pendingLlmCallTs = null;
        }
        // Start a new tool batch window after this response
        inToolBatch = true;
        batchHasCall = false;
        batchHasResult = false;
        batchMinCallTs = Infinity;
        batchMaxResultTs = -Infinity;
        break;
      }

      case "tool_call": {
        if (inToolBatch) {
          const t = tsMs(e.ts);
          if (!isNaN(t)) {
            batchHasCall = true;
            if (t < batchMinCallTs) batchMinCallTs = t;
          }
        }
        break;
      }

      case "tool_result": {
        if (inToolBatch) {
          const t = tsMs(e.ts);
          if (!isNaN(t)) {
            batchHasResult = true;
            if (t > batchMaxResultTs) batchMaxResultTs = t;
          }
        }
        break;
      }

      case "turn_end": {
        // Flush any trailing tool batch (shouldn't happen in normal flow, but be safe)
        if (inToolBatch && batchHasCall && batchHasResult) {
          const span = batchMaxResultTs - batchMinCallTs;
          if (span > 0) toolMs += span;
        }
        inToolBatch = false;

        if (userMessageTs !== null) {
          const endTs = tsMs(e.ts);
          if (!isNaN(endTs) && !isNaN(userMessageTs)) {
            turnMs = endTs - userMessageTs;
          }
        }
        break;
      }

      default:
        break;
    }
  }

  return { llmMs, toolMs, turnMs };
}

/**
 * Compute live (in-progress) duration metrics from a partial turn's event list.
 *
 * Same as computeDurations but:
 *  - turnMs is always 0 (no turn_end yet — we never use Date.now())
 *  - A pending tool batch is flushed as soon as all expected results have arrived
 *    (i.e. every tool_call.id has a matching tool_result.id).
 *
 * This is called incrementally on every new llm_response or tool_result event
 * so the display updates promptly.
 */
export function computeLiveDurations(events: WsEvent[]): DurationMetrics {
  // Re-use computeDurations on partial events. The only difference is that
  // an open tool batch at the end should be flushed if all tool_calls have results.
  let llmMs = 0;
  let toolMs = 0;

  let pendingLlmCallTs: number | null = null;
  let inToolBatch = false;
  let batchMinCallTs = Infinity;
  let batchMaxResultTs = -Infinity;
  // Track ids to detect when the last result has arrived
  const batchCallIds = new Set<string>();
  const batchResultIds = new Set<string>();

  for (const e of events) {
    switch (e.type) {
      case "llm_call": {
        // Flush completed batch before next LLM call
        if (inToolBatch && batchCallIds.size > 0 && batchCallIds.size === batchResultIds.size) {
          const span = batchMaxResultTs - batchMinCallTs;
          if (span > 0) toolMs += span;
        }
        inToolBatch = false;
        batchCallIds.clear();
        batchResultIds.clear();
        batchMinCallTs = Infinity;
        batchMaxResultTs = -Infinity;

        pendingLlmCallTs = tsMs(e.ts);
        break;
      }

      case "llm_response": {
        if (pendingLlmCallTs !== null) {
          const respTs = tsMs(e.ts);
          if (!isNaN(respTs) && !isNaN(pendingLlmCallTs)) {
            llmMs += respTs - pendingLlmCallTs;
          }
          pendingLlmCallTs = null;
        }
        inToolBatch = true;
        batchCallIds.clear();
        batchResultIds.clear();
        batchMinCallTs = Infinity;
        batchMaxResultTs = -Infinity;
        break;
      }

      case "tool_call": {
        if (inToolBatch) {
          batchCallIds.add(e.id);
          const t = tsMs(e.ts);
          if (!isNaN(t) && t < batchMinCallTs) batchMinCallTs = t;
        }
        break;
      }

      case "tool_result": {
        if (inToolBatch) {
          batchResultIds.add(e.id);
          const t = tsMs(e.ts);
          if (!isNaN(t) && t > batchMaxResultTs) batchMaxResultTs = t;

          // Flush if all calls have results
          if (batchCallIds.size > 0 && batchCallIds.size === batchResultIds.size) {
            const span = batchMaxResultTs - batchMinCallTs;
            if (span > 0) toolMs += span;
            // Reset so we don't double-count if more results arrive (shouldn't happen)
            batchCallIds.clear();
            batchResultIds.clear();
            batchMinCallTs = Infinity;
            batchMaxResultTs = -Infinity;
          }
        }
        break;
      }

      default:
        break;
    }
  }

  return { llmMs, toolMs, turnMs: 0 };
}

export function dispatch(event: WsEvent): void {
  switch (event.type) {
    case "connected":
      setState("connected", true);
      setState("streaming", false);
      setState("retryCount", 0);
      break;

    case "disconnected":
      setState("connected", false);
      setState("streaming", false);
      setState("retryCount", r => r + 1);
      break;

    case "history": {
      // Rebuild turns from the event log using plain JS objects, then set the
      // final result in one store write.  Previous approach dispatched each
      // event individually inside batch(), mixing array replacement with
      // produce-based mutation — this confused SolidJS's fine-grained change
      // tracking and left <For> with a stale reference after a page reload.
      const turns: Turn[] = [];
      let streaming = false;
      let tid = 0;
      let replayLastTurnEnd: LastTurnInfo | null = null;
      let replaySessionTotals: StickyMetrics = zeroMetrics();
      let replaySessionDurations: DurationMetrics = zeroDurations();
      let replayCompactionTotals: StickyMetrics = zeroMetrics();

      for (const e of event.events) {
        const cur = () => turns[turns.length - 1];

        switch (e.type) {
          case "user_message":
            turns.push({ id: tid++, events: [e], done: false });
            streaming = true;
            break;

          case "turn_end": {
            const t = cur();
            if (t) {
              t.events.push(e);
              t.done = true;
            }
            streaming = false;
            // Accumulate sticky metrics
            const turnEvents = t ? t.events : [];
            const sm = metricsFromTurnEnd(e, sumRequestBytes(turnEvents));
            const sd = computeDurations(turnEvents);
            replayLastTurnEnd = { metrics: sm, durations: sd, model: e.model, provider: e.provider };
            replaySessionTotals = addMetrics(replaySessionTotals, sm);
            replaySessionDurations = addDurations(replaySessionDurations, sd);
            break;
          }

          case "turn_interrupted": {
            const t = cur();
            if (t) {
              t.events.push(e);
              t.done = true;
            }
            streaming = false;
            break;
          }

          case "compact_auto_done":
          case "compact_user_done": {
            const u = (e as any).usage;
            if (u) replayCompactionTotals = addMetrics(replayCompactionTotals, {
              freshInTokens: u.input_tokens ?? 0,
              writeInTokens: u.cache_creation_input_tokens ?? 0,
              readInTokens:  u.cache_read_input_tokens ?? 0,
              outTokens:     u.output_tokens ?? 0,
              requestBytes:  0,
            });
            const t = cur();
            if (t) t.events.push(e);
            break;
          }

          // Transport-only events — never appear in persisted history,
          // but listed for completeness (server filters them out).
          case "connected":
          case "disconnected":
          case "history":
          case "auth":
          case "reset_done":
          case "session_info":
            break;

          // All other events: append to the current turn's event list.
          default: {
            const t = cur();
            if (t) t.events.push(e);
            break;
          }
        }
      }

      // If the last turn is still open (e.g. server reconnect mid-turn), compute
      // live durations from what we have so far.
      let replayLiveDurations = zeroDurations();
      if (streaming) {
        const t = turns[turns.length - 1];
        if (t) {
          // Close the turn with a synthetic interrupted marker for display
          t.events.push({ type: "turn_interrupted" });
          t.done = true;
          // Durations from partial events (turnMs will be 0)
          replayLiveDurations = computeLiveDurations(t.events);
        }
        streaming = false;
      }

      nextTurnId = tid;
      // Single batch write — SolidJS sees one atomic state transition.
      batch(() => {
        setState("turns", turns);
        setState("authMode", "");
        setState("streaming", false);
        setState("connected", true);
        setState("retryCount", 0);
        setState("lastTurnEnd", replayLastTurnEnd);
        setState("sessionTotals", replaySessionTotals);
        setState("sessionDurations", replaySessionDurations);
        setState("compactionTotals", replayCompactionTotals);
        setState("liveDurations", replayLiveDurations);
      });
      break;
    }

    case "auth":
      setState("authMode", event.mode);
      break;

    case "session_info":
      setState("sessionDir", event.dir);
      break;

    case "reset_done":
      // Server has created a new agent — clear all UI state
      setState("turns", []);
      setState("streaming", false);
      setState("lastTurnEnd", null);
      setState("sessionTotals", zeroMetrics());
      setState("sessionDurations", zeroDurations());
      setState("compactionTotals", zeroMetrics());
      setState("liveTurn", null);
      setState("liveDurations", zeroDurations());
      setState("liveProvider", "");
      setState("liveModel", "");
      nextTurnId = 0;
      break;

    case "user_message":
      // Start a new turn
      setState("turns", t => [...t, {
        id: nextTurnId++,
        events: [event],
        done: false,
      }]);
      setState("streaming", true);
      setState("liveTurn", zeroMetrics());
      setState("liveDurations", zeroDurations());
      break;

    case "text":
      // Accumulate streaming text fragments into the turn's temporary streamingText
      // slot. This is shown as a plain live preview below the event list, separate
      // from events[]. It is cleared when llm_response arrives (which carries the
      // settled text as its own field).
      setState(produce(s => {
        const turn = s.turns[s.turns.length - 1];
        if (!turn) return;
        turn.streamingText = (turn.streamingText ?? "") + event.text;
      }));
      break;

    case "turn_end": {
      setState(produce(s => {
        const turn = s.turns[s.turns.length - 1];
        if (turn) {
          turn.events.push(event);
          turn.done = true;
        }
      }));
      // turn_end means the agentic loop finished; clear streaming so replayed
      // history doesn't leave the UI stuck in streaming state.
      setState("streaming", false);
      // Compute durations from the now-complete turn events
      const currentTurnEvents = state.turns[state.turns.length - 1]?.events ?? [];
      const sd = computeDurations(currentTurnEvents);
      // Update sticky metrics and clear live accumulators
      const sm = metricsFromTurnEnd(event, sumRequestBytes(currentTurnEvents));
      setState("lastTurnEnd", { metrics: sm, durations: sd, model: event.model, provider: event.provider });
      setState("sessionTotals", prev => addMetrics(prev, sm));
      setState("sessionDurations", prev => addDurations(prev, sd));
      setState("liveTurn", null);
      setState("liveDurations", zeroDurations());
      break;
    }

    case "turn_interrupted":
      setState(produce(s => {
        const turn = s.turns[s.turns.length - 1];
        if (turn) {
          turn.events.push(event);
          turn.done = true;
        }
      }));
      setState("streaming", false);
      setState("liveTurn", null);
      setState("liveDurations", zeroDurations());
      break;

    case "llm_response": {
      // Append to turn first so computeLiveDurations sees the new event
      setState(produce(s => {
        const turn = s.turns[s.turns.length - 1];
        if (!turn) return;
        turn.streamingText = undefined;
        turn.events.push(event);
      }));
      // Recompute live durations from the updated turn events (llmMs ticks up)
      const turnEventsAfterResp = state.turns[state.turns.length - 1]?.events ?? [];
      setState("liveDurations", computeLiveDurations(turnEventsAfterResp));
      // Accumulate live per-turn token totals so the metrics bar ticks up mid-turn.
      const u = event.usage;
      setState("liveTurn", prev => {
        if (!prev) return prev;
        return {
          freshInTokens:  prev.freshInTokens  + u.input_tokens,
          writeInTokens:  prev.writeInTokens  + (u.cache_creation_input_tokens ?? 0),
          readInTokens:   prev.readInTokens   + (u.cache_read_input_tokens ?? 0),
          outTokens:      prev.outTokens      + u.output_tokens,
          requestBytes:   prev.requestBytes,
        };
      });
      break;
    }

    case "session_start": {
      appendEvent(event);
      setState("liveProvider", event.provider);
      setState("liveModel", event.model);
      break;
    }

    case "llm_call": {
      appendEvent(event);
      setState("liveProvider", event.provider);
      setState("liveModel", event.model);
      // Tick up requestBytes in the live turn accumulator
      setState("liveTurn", prev => {
        if (!prev) return prev;
        return { ...prev, requestBytes: prev.requestBytes + (event.requestBytes ?? 0) };
      });
      break;
    }

    case "tool_result": {
      // Append first so computeLiveDurations sees the new result
      setState(produce(s => {
        const turn = s.turns[s.turns.length - 1];
        if (turn) turn.events.push(event);
      }));
      // Recompute live durations (toolMs may tick up when last result of batch arrives)
      const turnEventsAfterResult = state.turns[state.turns.length - 1]?.events ?? [];
      setState("liveDurations", computeLiveDurations(turnEventsAfterResult));
      break;
    }

    case "session_end":
    case "tool_call":
    case "llm_retry":
    case "model_changed":
    case "oauth_token_expired":
    case "oauth_refreshed":
    case "compact_auto_done":
    case "compact_user_done": {
      appendEvent(event);
      const u = (event as any).usage;
      if (u) setState("compactionTotals", prev => addMetrics(prev, {
        freshInTokens: u.input_tokens ?? 0,
        writeInTokens: u.cache_creation_input_tokens ?? 0,
        readInTokens:  u.cache_read_input_tokens ?? 0,
        outTokens:     u.output_tokens ?? 0,
        requestBytes:  0,
      }));
      break;
    }

    case "compact_user_start":
    case "compact_user_error":
    case "compact_auto_start":
    case "compact_auto_error":
    case "world_state_saved":
    case "llm_error":
    case "agent_error":
    case "error":
      appendEvent(event);
      break;
  }
}
